spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/troyboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    ip: 127.0.0.1
    port: 3306
    catalog: troyboot
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        min-idle: 10
        max-active: 100
        max-wait: -1
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: info
    com.troyboot.java: info
  file: logs/dev.log
