server:
  session-timeout: 1800
  address: 127.0.0.1
  port: 9264
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  http:
      encoding:
        charset: utf-8
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
  cache:
      type: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.troyboot.java.**.**
  type-handlers-package: com.troyboot.java
