server:
  session-timeout: 1800
  address: 127.0.0.1
  port: 9264
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  datasource:
    # HikariCP数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: TroyBoot-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  http:
      encoding:
        charset: utf-8
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
  cache:
      type: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/**.xml
  type-aliases-package: com.troyboot.java.system.po
  type-handlers-package: com.troyboot.java
# 分页插件
pagehelper:
  # 可选数据库oracle , mysql , mariadb , sqlite , hsqldb , postgresql , db2 , sqlserver , informix , h2 , sqlserver2012 , derby
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
